### ISSUE TITLE
can it be possible only fetch base and UI library with some script automatically?

### ISSUE THREAD

**Issue by hongnod** [zcbenz/chromium-source-tarball#1]
this project is amazing for reducing the work-complex to fetch the entire codebase of  Chromium. I wonder if there some one to write a piece of script to fetch the desire part of the code, such a base lib and ui library. the two base library cab be used in developer's own project.

**Comment by zcbenz** [comment]
The `base` and `ui` libraries rely on lots of other dependencies, it is nearly impossible to only fetch desired parts and make things work. You can just have a try yourself.

**Comment by glensc** [comment]
you may try (i no specified order), may solve your needs

https://github.com/atom/libchromiumcontent
https://github.com/cybertk/libchromium
https://www.chromium.org/chromium-os/packages/libchrome

**Comment by hongnod** [comment]
@glensc ,thanks,
`https://github.com/atom/libchromiumcontent` looks good.
