### ISSUE TITLE
wrong version contents

### ISSUE THREAD

**Issue by glensc** [zcbenz/chromium-source-tarball#2]
```
set -xe
wget https://github.com/zcbenz/chromium-source-tarball/releases/download/49.0.2623.47/chromium-49.0.2623.47.tar.xz
tar xf chromium-49.0.2623.47.tar.xz
cd chromium-49.0.2623.47
. ./chrome/VERSION
chrome=$MAJOR.$MINOR.$BUILD.$PATCH
test "$chrome" =49.0.2623.47
```

```
+ . ./chrome/VERSION
+ MAJOR=50
+ MINOR=0
+ BUILD=2646
+ PATCH=0
+ chrome=50.0.2646.0
+ test 50.0.2646.0 '=' 49.0.2623.47
```

i guess such sanity check would be handy.

**Comment by zcbenz** [comment]
We got some errors with the sync script, the 50.0.2661.87 source tarball is fixed now.

**Comment by glensc** [comment]
pasting fixes as reference back to issue
efff32ccef3ee850b8b6f09ae0d0a9180a5450d1
fa3abf37a14e50a1486c2d7ee7c761f4addc0b4c

next time you could used just ticket reference `#2` so they would be linked automatically here by github

**Comment by glensc** [comment]
altho your fixes will now ignore errors. shouldn't it be opposite that script aborts whole tarball process when an error is encountered in sync process?
