### ISSUE TITLE
"--test-data" by default?

### ISSUE THREAD

**Issue by brianh5** [zcbenz/chromium-source-tarball#5]
Sorry, I don't think an issue is appropriate for this, but wasn't sure how else to ask the question.  I notice that "--test-data" is set by default in the update script, and this only gives tarballs of ~30kb, whereas I'm looking to build the ~500mb tarballs with the entire chromium source (minus anything non-essential).  When I remove the "--test-data" flag, I get a tar that is much, much bigger (multiple gigs).  Is there something I'm missing?

**Comment by zcbenz** [comment]
I thought `--test-data` would include both src and test datas, but it seems that it only includes the test data, I'll fix that.

> When I remove the "--test-data" flag, I get a tar that is much, much bigger (multiple gigs). Is there something I'm missing?

The script doesn't filter out your local builds, that's probably the reason.

**Comment by brianh5** [comment]
hey thanks for the response.

> The script doesn't filter out your local builds, that's probably the reason.

you mean the build files?  looks like you're right.  i swore that i ran it without my local build (and just tried to recreate the one that was unzipped from sync), but looks like i was wrong.  i get a 2.8gb tar that compresses to a 490mb tar.xz, perhaps i saw the tar file size and underestimated xz's compression.  anyways, thanks!
